#!/bin/bash
#echo "list disk" >test1.txt
echo "list disk" | ssh jakubr@$1 '  diskpart  ' |grep Online |  awk -e '{printf("%s       %s %s %s\n",$4,$5,$2,$6);}' |uniq -D -w 7 | awk -e '{ if ($4 != '0' ) print($3" "$4) ;}' | wc -l 
#|grep "Partition" |grep -v Boot | awk -e '{print($7,$8,$4,$2);}' |uniq -D -w 7 | awk -e '{printf("select volume %s\n extend \n",$4 );}'
