all:
    hosts:
        centos:
            ansible_host: 192.168.1.25
        virto:
            ansible_host: 192.168.1.6
    children:
        virto_hosts:
            hosts:
                virto:
        local_hosts:
            hosts:
                centos:
        

