all:
    hosts:
        docker:
            ansible_host: 192.168.1.26
        centos:
            ansible_host: 192.168.1.25
    children:
        remote-hosts:
            hosts:
                docker:
        local-hosts:
            hosts:
                centos:

